baseURL = 'https://ryancontento.dev/'
title = 'Ryan Contento Blog'
theme = "simple-blog"
copyright = "© 2020 copyright text."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"

[params]

